/**
 * Sulfur backend
 * El login exitoso de AuthService devuelve un Usuario con un campo \"token\". Dicho token se debe incluir como header de las llamadas del resto de las operaciones de cada servicio.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';
import { UnidadMedida } from './UnidadMedida';

export interface Material {
    id?: number;

    codigo: string;

    nombre?: string;

    descripcion?: string;

    codigoAlternativo: string;

    stock: boolean;

    medida1: UnidadMedida;

    medida2: UnidadMedida;

    factorConversion2: number;

    medida3: UnidadMedida;

    factorConversion3: number;

    tipoMaterial?: models.TipoMaterial;

    nucleoMaterial?: models.NucleoMaterial;
}
